### ISSUE TITLE
Nav-bar

### ISSUE THREAD

**Issue by kiranmurali93** [Make-a-Ton/website-2020#1]
Change of selected section in nav bar(blue-line)
![Selection_023](https://user-images.githubusercontent.com/44119868/93583365-62cfa080-f9c1-11ea-9f11-316b58872cac.png)
The underline should be under the selected section (under sponsors)

![Selection_022](https://user-images.githubusercontent.com/44119868/93583370-6400cd80-f9c1-11ea-8737-5d186e39b638.png)
(under Team)

**Comment by naseemshah** [comment]
sure working on that.
