### ISSUE TITLE
Footer responsiveness 

### ISSUE THREAD

**Issue by kiranmurali93** [Make-a-Ton/website-2020#2]
![Selection_024](https://user-images.githubusercontent.com/44119868/93583671-cc4faf00-f9c1-11ea-958b-656122115839.png)
![Selection_025](https://user-images.githubusercontent.com/44119868/93583687-d1acf980-f9c1-11ea-96ee-4a056cd6daff.png)

**Comment by abhinav-TB** [comment]
this was fixed long ago , i rechecked now and did not find this problem, could you try in incognito mode
